import 'bible_library.dart';

class ReadingPlanDef {
  const ReadingPlanDef({
    required this.key,
    required this.name,
    required this.sub,
    required this.totalDays,
    required this.bookSelector,
  });

  final String key;
  final String name;
  final String sub;
  final int totalDays;

  /// Which books (in reading order) this plan covers, resolved against the
  /// loaded library so chapter counts always match the real text.
  final List<String> Function(BibleLibrary) bookSelector;
}

final readingPlanDefs = <String, ReadingPlanDef>{
  'oneYear': ReadingPlanDef(
    key: 'oneYear',
    name: 'One Year Bible',
    sub: '365 days · Gen–Rev',
    totalDays: 365,
    bookSelector: (lib) => lib.books.map((b) => b.name).toList(),
  ),
  'ninety': ReadingPlanDef(
    key: 'ninety',
    name: 'Bible in 90 Days',
    sub: '90 days',
    totalDays: 90,
    bookSelector: (lib) => lib.books.map((b) => b.name).toList(),
  ),
  'nt': ReadingPlanDef(
    key: 'nt',
    name: 'New Testament',
    sub: '60 days',
    totalDays: 60,
    bookSelector: (lib) => lib.books.where((b) => b.testament == 'NT').map((b) => b.name).toList(),
  ),
  'psalms': ReadingPlanDef(
    key: 'psalms',
    name: 'Psalms & Proverbs',
    sub: '31 days',
    totalDays: 31,
    bookSelector: (lib) => const ['Psalms', 'Proverbs'],
  ),
};

/// A day-by-day chapter schedule for one plan, generated by evenly
/// distributing every chapter of the plan's books across its total days —
/// so "today's reading" is always a real, correctly-ordered passage rather
/// than a hardcoded string.
class ReadingPlanSchedule {
  ReadingPlanSchedule._(this.def, this._byDay);

  final ReadingPlanDef def;
  final List<List<(String book, int chapter)>> _byDay;

  factory ReadingPlanSchedule.build(ReadingPlanDef def, BibleLibrary library) {
    final books = def.bookSelector(library);
    final chapters = <(String, int)>[];
    for (final book in books) {
      final count = library.chapterCountFor(book);
      for (var ch = 1; ch <= count; ch++) {
        chapters.add((book, ch));
      }
    }

    final byDay = List<List<(String, int)>>.generate(def.totalDays, (_) => const []);
    final total = chapters.length;
    for (var day = 0; day < def.totalDays; day++) {
      final start = (total * day) ~/ def.totalDays;
      final end = (total * (day + 1)) ~/ def.totalDays;
      byDay[day] = chapters.sublist(start, end);
    }
    return ReadingPlanSchedule._(def, byDay);
  }

  /// 1-indexed day, clamped to the plan's range.
  List<(String, int)> readingsForDay(int day) {
    if (_byDay.isEmpty) return const [];
    final index = day.clamp(1, def.totalDays) - 1;
    return _byDay[index];
  }

  /// The first (book, chapter) of [day] — where "Read now" should open.
  (String, int)? firstOf(int day) {
    final readings = readingsForDay(day);
    return readings.isEmpty ? null : readings.first;
  }

  String label(int day) {
    final readings = readingsForDay(day);
    if (readings.isEmpty) return '';
    final parts = <String>[];
    var book = readings.first.$1;
    var rangeStart = readings.first.$2;
    var rangeEnd = readings.first.$2;
    for (var i = 1; i <= readings.length; i++) {
      final atEnd = i == readings.length;
      final next = atEnd ? null : readings[i];
      if (!atEnd && next!.$1 == book && next.$2 == rangeEnd + 1) {
        rangeEnd = next.$2;
        continue;
      }
      parts.add(rangeStart == rangeEnd ? '$book $rangeStart' : '$book $rangeStart–$rangeEnd');
      if (!atEnd) {
        book = next!.$1;
        rangeStart = next.$2;
        rangeEnd = next.$2;
      }
    }
    return parts.join(' · ');
  }
}
